#!/usr/bin/env bash
set -euo pipefail

# Override these values inline when needed, for example:
# EXT_JNJ_IAM_CLIENT_ID=other-client EXT_JNJ_MOCK_AUTHORIZATION_TOKEN=false npm run dev:local

: "${EXT_JNJ_ROOT_URL:=http://localhost:3000}"
: "${EXT_JNJ_IAM_URL:=https://localhost}"
: "${EXT_JNJ_IAM_REALM_NAME:=phnc-dev}"
: "${EXT_JNJ_IAM_CLIENT_ID:=phnc-test-app}"
: "${EXT_JNJ_IAM_SCOPE:=openid profile email nucleus}"
: "${EXT_JNJ_IAM_STARTUP_MODE:=login-required}"
: "${EXT_JNJ_IAM_REDIRECT_URI:=${EXT_JNJ_ROOT_URL%/}/signin}"
: "${EXT_JNJ_IAM_POST_LOGOUT_REDIRECT_URI:=${EXT_JNJ_ROOT_URL%/}/}"
: "${EXT_JNJ_IAM_SILENT_CHECK_SSO_REDIRECT_URI:=${EXT_JNJ_ROOT_URL%/}/sso-signin}"
: "${EXT_JNJ_IAM_SILENT_CHECK_SSO_ENABLED:=false}"
: "${EXT_JNJ_TMS_V2_ROOT_URL:=${EXT_JNJ_ROOT_URL%/}}"
: "${EXT_JNJ_TENANT_ID:=}"
: "${EXT_JNJ_MOCK_AUTHORIZATION_TOKEN:=true}"
: "${EXT_JNJ_MOCK_AUTHORIZATION_APP:=${EXT_JNJ_IAM_CLIENT_ID}}"
: "${EXT_JNJ_MOCK_AUTHORIZATION_TENANT:=local-test}"
: "${EXT_JNJ_MOCK_AUTHORIZATION_ROLES:=user}"
: "${EXT_JNJ_IAM_USER_INACTIVITY_TIMEOUT:=900000}"
: "${EXT_JNJ_IAM_INACTIVITY_WARNING_TIMEOUT:=60000}"

export EXT_JNJ_ROOT_URL
export EXT_JNJ_IAM_URL
export EXT_JNJ_IAM_REALM_NAME
export EXT_JNJ_IAM_CLIENT_ID
export EXT_JNJ_IAM_SCOPE
export EXT_JNJ_IAM_STARTUP_MODE
export EXT_JNJ_IAM_REDIRECT_URI
export EXT_JNJ_IAM_POST_LOGOUT_REDIRECT_URI
export EXT_JNJ_IAM_SILENT_CHECK_SSO_REDIRECT_URI
export EXT_JNJ_IAM_SILENT_CHECK_SSO_ENABLED
export EXT_JNJ_TMS_V2_ROOT_URL
export EXT_JNJ_TENANT_ID
export EXT_JNJ_MOCK_AUTHORIZATION_TOKEN
export EXT_JNJ_MOCK_AUTHORIZATION_APP
export EXT_JNJ_MOCK_AUTHORIZATION_TENANT
export EXT_JNJ_MOCK_AUTHORIZATION_ROLES
export EXT_JNJ_IAM_USER_INACTIVITY_TIMEOUT
export EXT_JNJ_IAM_INACTIVITY_WARNING_TIMEOUT

npm run dev
